[tool.black]
line-length = 120

[tool.ruff]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120
force_sort_within_sections = true
combine_as_imports = true
known_first_party = [
    "custom_components.yandex_smart_home",
    "tests",
]
skip_glob = [".venv*/*"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.coverage.report]
exclude_also = [
    "raise NotImplementedError",
    "@abstractmethod"
]
omit = [
    "tests/*"
]
